- hosts: zookeeper
  remote_user: vagrant
  serial: 100%
  roles:
    - {role: zookeeper, tags: zookeeper}

- hosts: kafka
  remote_user: vagrant
  serial: 100%
  roles:
    - {role: kafka, tags: kafka}
