- hosts: all
  remote_user: vagrant
  serial: 100%
  roles:
    - java

- hosts: zookeeper
  remote_user: vagrant
  serial: 66%
  roles:
    - zookeeper

- hosts: kafka
  remote_user: vagrant
  serial: 66%
  roles:
    - kafka
